services:
  api:
    build:
      context: ./CultureEvents.API
      dockerfile: Dockerfile
    ports:
      - "5165:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb+srv://tcacidoliviu:WCHKfPG01HGnyYJL@cluster0.gvq8w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MongoDbSettings__DatabaseName=CultureEventsDb
    volumes:
      - api-keys:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - culture-events-network

  frontend:
    build:
      context: ./CultureEventsManager
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - culture-events-network

volumes:
  api-keys:
    driver: local

networks:
  culture-events-network:
    driver: bridge
